from datetime import datetime, timedelta, timezone

from .schemas import ActionType, AuthorityEnvelope


_AUTHORITIES: dict[str, AuthorityEnvelope] = {}


def create_authority(
    authority_id: str,
    agent_id: str,
    merchant_id: str,
    product_id: str,
    max_amount: int,
) -> AuthorityEnvelope:
    """
    Create and store a server-controlled authority envelope.

    The authority is generated by the control plane rather than
    being supplied by the AI agent.
    """

    authority = AuthorityEnvelope(
        authority_id=authority_id,
        agent_id=agent_id,
        allowed_action=ActionType.PURCHASE,
        merchant_id=merchant_id,
        product_id=product_id,
        max_amount=max_amount,
        currency="INR",
        requires_inventory=True,
        requires_price_revalidation=True,
        expires_at=datetime.now(timezone.utc) + timedelta(hours=24),
    )

    _AUTHORITIES[authority_id] = authority

    return authority


def get_authority(authority_id: str) -> AuthorityEnvelope:
    """
    Retrieve the authoritative policy from the server-side store.
    """

    authority = _AUTHORITIES.get(authority_id)

    if authority is None:
        raise KeyError(f"Authority '{authority_id}' was not found.")

    return authority