from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class ActionType(str, Enum):
    PURCHASE = "PURCHASE"


class UserIntent(BaseModel):
    """
    The user's original commerce request.

    This represents what the user actually asked the agent to do.
    """

    request: str
    category: str
    size: int | None = None
    max_amount: int = Field(gt=0)
    currency: str = "INR"


class TransactionProposal(BaseModel):
    """
    A proposed financial action generated by the AI agent.

    This is a proposal, NOT authorization.
    """

    action: ActionType
    product_id: str
    merchant_id: str
    amount: int = Field(gt=0)
    currency: str = "INR"
    quantity: int = Field(default=1, gt=0)


class AuthorityEnvelope(BaseModel):
    """
    The deterministic limits delegated to the AI agent.

    The AI agent must never be able to increase these limits.
    """

    authority_id: str
    agent_id: str

    allowed_action: ActionType

    merchant_id: str
    product_id: str

    max_amount: int = Field(gt=0)
    currency: str = "INR"

    requires_inventory: bool = True
    requires_price_revalidation: bool = True

    expires_at: datetime


class MerchantProduct(BaseModel):
    """
    Current merchant-side state for a product.

    This is the state we revalidate immediately before payment.
    """

    product_id: str
    merchant_id: str

    name: str
    category: str

    price: int
    currency: str = "INR"

    available_sizes: list[int] = Field(default_factory=list)
    inventory: int = Field(ge=0)


class PolicyDecision(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    REAUTHORIZE = "REAUTHORIZE"


class PolicyResult(BaseModel):
    """
    Deterministic result produced by the policy engine.

    The AI does not decide this value.
    """

    decision: PolicyDecision
    reasons: list[str] = Field(default_factory=list)
    
class Transaction(BaseModel):
    transaction_id: str
    authority_id: str
    proposal: TransactionProposal
    state: str

    # Razorpay identifiers are populated only after
    # the server creates the payment order.
    razorpay_order_id: str | None = None
    razorpay_payment_id: str | None = None